### ISSUE TITLE
DataTables warning: table id=mytable- Ajax error. 

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables#171]
can I ask some help why it is not working.is there some files that are missing ?

Thank you in advance.

```
  $(function() {
            $('#mytable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '/admin/enrollment/all_list'


            });
        });

```

//routes.php

```
Route::get('admin/enrollment/all_list', 'Admin\EnrollmentController@getEnroll');


```

//EnrollmentController

```
  public function getEnroll(){

        $users = User::select(['studentid','fname','lname']);
        return Datatables::of($users)->make();

    }


```

**Comment by yajra** [comment]
Can you paste your table markup? It should look something like below. TH should match the selected columns. And also make sure you have at least v1.10.x of datatables.

```html
<table id="mytable">
  <thead>
    <tr>
      <th>Id</th>
      <th>FName</th>
      <th>LName</th>
    </tr>
  </thead> 
</table>
```

**Comment by ezekel** [comment]
@yajra ,

here it is

```
 <table class="table table-striped table-bordered table-hover" width="100%" id="mytable">
                                    <thead>
                                    <tr>

                                        <th></th>
                                        <th>ID</th>
                                        <th>FIRSTNAME</th>
                                        <th>LASTNAME</th>
                                    </tr>
                                    </thead>
                                </table>
```

**Comment by yajra** [comment]
You have extra `<th></th>` which may have cause the issue.

**Comment by ezekel** [comment]
@yajra ,

Thank you so much

**Comment by ezekel** [comment]
@yajra ,

why is it i have different loading icon in your demo ?

**Comment by yajra** [comment]
My demo have a customized css and loading image. You can copy it if you like.

**Comment by ezekel** [comment]
which file to copy the loading image ?

**Comment by yajra** [comment]
`/public/css/datatables.bootstrap.css` and `/public/images/loading_bar.gif` or try adding this on your css.

```css
.dataTables_processing {
    position: absolute;
    top: 50%;
    left: 50%;
    width: 250px;
    height: 80px;
    margin-left: -125px;
    margin-top: -15px;
    padding: 15px 0 30px 0;
    border: 1px solid #ddd;
    text-align: center;
    color: #444;
    font-size: 14px;
    background: url("../images/loading_bar.gif") no-repeat center 38px #fff;
    box-shadow: 2px 2px 5px #444;
    -moz-box-shadow: 2px 2px 5px #444;
    -webkit-box-shadow: 2px 2px 5px #444;
    z-index: 9999;
}
```
