### ISSUE TITLE
I want to show custom loader using html builder

### ISSUE THREAD

**Issue by UrvishTechnource** [yajra/laravel-datatables#2581]
$('#degree_listing').on('processing.dt', function (e, settings, processing) {
    if (processing) {
      showLoader(true);
    } else {
      showLoader(false);
    }
  })
  
  I was defining the custom loader method on processing events in JS. Now I want to implement this logic in the parameters method how I can write it?
  
Builder Method
 $dt_html = $builder
            ->addIndex()
            ->columns([
                ['data' => 'DT_RowIndex', 'name' => 'pkAcd', 'title' => trans('general.sr_no'), 'render' => null, 'orderable' => false, 'searchable' => false],
                ['data' => 'acd_Uid', 'name' => 'acd_Uid', 'title' => trans('general.gn_uid')],
                ['data' => 'acd_AcademicDegreeName', 'name' => 'acd_AcademicDegreeName', 'title' => trans('general.gn_name')],
                ['data' => 'acd_Notes', 'name' => 'acd_Notes', 'title' => trans('general.gn_notes')],
                ['data' => 'action', 'name' => 'action', 'title' => trans('general.gn_actions'), 'orderable' => false, 'searchable' => false, 'width' => '10%'],
            ])
            ->ajax([
                'url'=> route('academicdegree.index',['request'=>'ajax_listing']),
                'data' => 'function(d) {
                    d.search =  $("#search_academic_degree").val();
                }'
            ])
            ->parameters([
                'searching' => false,
                'lengthMenu' => [10, 20, 30, 50],
                'language' => [
                    'sLengthMenu' => trans('general.gn_show') . " _MENU_ " . trans('general.gn_entries'),
                    'info' => trans('general.gn_showing') ." _START_ ". trans('general.gn_to') ." _END_ ". trans('general.gn_of'),
                    'emptyTable' => trans('message.msg_no_data_available_table'),
                    'paginate' => [
                        'previous' => trans('general.gn_previous'),
                        'next' => trans('general.gn_next')
                    ]
                    ],
                'drawCallback'=> '',
            ]);
            
Because I am struggling to find such a custom solution in a document.
Thanks in advance.

**Comment by schonhoff** [comment]
Hello,

I'm not using the html builder, but in dataTables there is an option for showing a process icon:

```js
processing: true,
```

After that is set, the table will get a class named ```dataTables_processing``` which can be customized in a css file. Maybe that will help you.  

```scss

div.dataTables_wrapper div.grey-out {
	div.dataTables_processing {
		position: absolute !important;
		width: 100% !important;
		height: 100% !important;
		z-index: 1010;
		background-color: rgba(33,33,33,0.5);
		margin: 0 !important;
		padding: 0 !important;
		top: 0 !important;
		left: 0 !important;

		div.dt-processing-text {
			position: relative !important;
			top: 50%;
			left: 50%;
			width: 200px;
			margin-left: -100px;
			margin-top: -26px;
			text-align: center;
			padding: 1em 0;
		}
	}
}
```

The greyed_out table is my custom css class for tables which I want a the background to be grey for the loading process.
