### ISSUE TITLE
Can't modify css loading animation

### ISSUE THREAD

**Issue by lanea07** [yajra/laravel-datatables#2887]
I have a DataTable which I'm customizing and I want to modify the loading css animation that comes by default. I've been able to add my custom animation, but I can't override the three dots that comes by default. Also, for some reason which I still don'k know, sometimes my animation doesn't show up. How can I use an modified animation?

PHP DataTable Class HTML Builder
```php
   public function html(): HtmlBuilder
    {
        return $this->builder()
                    ->setTableId('directorio-table')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->dom('
                            <"d-flex"
                                <"mx-2"B>
                                <"m-2"l>
                                <"m-2 ms-auto"f>
                            >
                            <tr>
                            <"d-flex"
                                <"mx-2"i>
                                <"mx-2 ms-auto"p>
                            >'
                        )
                    ->orderBy(0, 'asc')
                    ->parameters([
                        'responsive' => true,
                        'buttons' => [
                            [
                                'extend' => 'excel',
                                'text' => '<i class="fas fa-file-excel fa-lg"></i><span class="ml-2">A Excel</span>',
                                'className' => 'btn btn-sm btn-success m-2',
                            ]
                        ],
                        'language' => [
                            'processing' => '<span class="loader"></span>',
                        ]
                    ]);
    }
```

CSS Style for the processing animation

```css
.loader {
    width: 150px;
    height: 150px;
    background-color: #ff3d00;
    border-radius: 50%;
    position: relative;
    box-shadow: 0 0 30px 4px rgba(0, 0, 0, 0.5) inset,
      0 5px 12px rgba(0, 0, 0, 0.15);
    overflow: hidden;
  }
  .loader:before,
  .loader:after {
    content: "";
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: 45%;
    top: -40%;
    background-color: #fff;
    animation: wave 5s linear infinite;
  }
  .loader:before {
    border-radius: 30%;
    background: rgba(255, 255, 255, 0.4);
    animation: wave 5s linear infinite;
  }
  @keyframes wave {
    0% {
      transform: rotate(0);
    }
    100% {
      transform: rotate(360deg);
    }
  }
```

**Comment by yajra** [comment]
I think what you should be overriding is the `dataTables_processing` class instead.

**Comment by lanea07** [comment]
You mean by using jquery or similar?

**Comment by yajra** [comment]
`.dataTables_processing` is the default CSS class for processing.  

```css
.dataTables_processing {
    width: 150px;
    height: 150px;
    background-color: #ff3d00;
    border-radius: 50%;
    position: relative;
    box-shadow: 0 0 30px 4px rgba(0, 0, 0, 0.5) inset,
      0 5px 12px rgba(0, 0, 0, 0.15);
    overflow: hidden;
  }

...
````
